---
abstract: 'A generic data container'
author:
  - 'Scott Yourstone <scott.yourstone81@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DataObj
provides:
  DataObj:
    file: lib/DataObj.pm
    version: v0.0.1
requires:
  Test::More: '0'
  version: '0'
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.014'
